// Package: com.lightningkite.rxexample.api
// Generated by Khrysalis - this file will be overwritten.
import { APIInterface } from './APIInterface'
import { APIOnline } from './APIOnline'

//! Declares com.lightningkite.rxexample.api.API
export let _API: APIInterface = new APIOnline(undefined);
export function getAPI(): APIInterface { return _API; }
export function setAPI(value: APIInterface) { _API = value; }
