// File: /home/jivie/Projects/khrysalis-full-example/android/src/main/java/com/lightningkite/rxexample/api/APIInterface.kt
// Package: com.lightningkite.rxexample.api
// Generated by Khrysalis - this file will be overwritten.
import { Post } from '../models/Post'
import { Observable } from 'rxjs'

//! Declares com.lightningkite.rxexample.api.APIInterface
export interface APIInterface {
    
    getExamplePosts(): Observable<Array<Post>>
}

