// File: /home/jivie/Projects/khrysalis-full-example/android/src/main/java/com/lightningkite/rxexample/api/APIMock.kt
// Package: com.lightningkite.rxexample.api
// Generated by Khrysalis - this file will be overwritten.
import { Post } from '../models/Post'
import { APIInterface } from './APIInterface'
import { delay } from 'rxjs/operators'
import { Observable, of } from 'rxjs'

//! Declares com.lightningkite.rxexample.api.APIMock
export class APIMock implements APIInterface {
    public static implementsAPIInterface = true;
    public constructor() {
    }
    
    
    
    
    public getExamplePosts(): Observable<Array<Post>> {
        return of([new Post(undefined, undefined, "First", APIMock.Companion.INSTANCE.lorem)]).pipe(delay(1000));
    }
}
export namespace APIMock {
    //! Declares com.lightningkite.rxexample.api.APIMock.Companion
    export class Companion {
        private constructor() {
            this.delayMs = 150;
            this.lorem = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";
        }
        public static INSTANCE = new Companion();
        
        public delayMs: number;
        public readonly lorem: string;
    }
}
