// File: /home/jivie/Projects/khrysalis-full-example/android/src/main/java/com/lightningkite/rxexample/api/APIOnline.kt
// Package: com.lightningkite.rxexample.api
// Generated by Khrysalis - this file will be overwritten.
import { Post } from '../models/Post'
import { APIInterface } from './APIInterface'
import { Observable } from 'rxjs'
import { HttpClient, fromJSON, unsuccessfulAsError } from '@lightningkite/rxjs-plus'

//! Declares com.lightningkite.rxexample.api.APIOnline
export class APIOnline implements APIInterface {
    public static implementsAPIInterface = true;
    public readonly baseUrl: string;
    public constructor(baseUrl: string = "https://jsonplaceholder.typicode.com") {
        this.baseUrl = baseUrl;
    }
    
    public getExamplePosts(): Observable<Array<Post>> {
        return HttpClient.INSTANCE.call(this.baseUrl + "/posts", HttpClient.INSTANCE.GET, new Map([]), undefined, undefined).pipe(unsuccessfulAsError, fromJSON<Array<Post>>([Array, [Post]]));
    }
    
}
