// Package: com.lightningkite.rxexample.api
// Generated by Khrysalis - this file will be overwritten.
import { Post } from '../models/Post'
import { APIInterface } from './APIInterface'
import { HttpClient, fromJSON, unsuccessfulAsError } from '@lightningkite/rxjs-plus'
import { Observable } from 'rxjs'

//! Declares com.lightningkite.rxexample.api.APIOnline
export class APIOnline implements APIInterface {
    public static implementsAPIInterface = true;
    public constructor(public readonly baseUrl: string = "https://jsonplaceholder.typicode.com") {
    }
    
    public getExamplePosts(): Observable<Array<Post>> {
        return HttpClient.INSTANCE.call(this.baseUrl + "/posts", HttpClient.INSTANCE.GET, new Map([]), undefined, undefined).pipe(unsuccessfulAsError, fromJSON<Array<Post>>([Array, [Post]]));
    }
    
}
