// Package: com.lightningkite.rxexample.models
// Generated by Khrysalis - this file will be overwritten.
import { ReifiedType, setUpDataClass } from '@lightningkite/khrysalis-runtime'

//! Declares com.lightningkite.rxexample.models.Post
export class Post {
    public constructor(public userId: number = 0, public id: number = 0, public title: string = "", public body: string = "") {
    }
    public static properties = ["userId", "id", "title", "body"]
    public static propertyTypes() { return {userId: [Number], id: [Number], title: [String], body: [String]} }
    copy: (values: Partial<Post>) => this;
    equals: (other: any) => boolean;
    hashCode: () => number;
}
setUpDataClass(Post)
