// Package: com.lightningkite.rxexample.vg
// Generated by Khrysalis - this file will be overwritten.
import { DateButtonDemoBinding } from '../resources/layouts/DateButtonDemoBinding'
import { HasTitle } from './HasTitle'
import { LocalDate, LocalDateTime, LocalTime, ZonedDateTime, convert, nativeJs } from '@js-joda/core'
import { FormatStyle, ofLocalizedDateTime } from '@lightningkite/khrysalis-runtime'
import { ViewGenerator, bind, buttonDate, mapSubject, mapSubjectWithExisting, subscribeAutoDispose } from '@lightningkite/rxjs-plus'
import { BehaviorSubject } from 'rxjs'
import { map } from 'rxjs/operators'

//! Declares com.lightningkite.rxexample.vg.DateButtonDemoVG
export class DateButtonDemoVG implements ViewGenerator, HasTitle {
    public static implementsViewGenerator = true;
    public static implementsHasTitle = true;
    public constructor() {
        this.date = new BehaviorSubject(ZonedDateTime.now());
    }
    
    //! Declares com.lightningkite.rxexample.vg.DateButtonDemoVG.title
    public get title(): string { return "ZonedDateTime Button Demo"; }
    
    
    public readonly date: BehaviorSubject<ZonedDateTime>;
    
    public generate(dependency: Window): HTMLElement {
        const xml = DateButtonDemoBinding.inflate();
        const view = xml.root;
        
        this.date.pipe(map((it: ZonedDateTime): string => (it.format(ofLocalizedDateTime(FormatStyle.MEDIUM, FormatStyle.MEDIUM))))).pipe(subscribeAutoDispose(xml.text, "textContent"));
        this.date.pipe(mapSubjectWithExisting(x => x.toLocalDate(), (a, b) => a.with(b))).pipe(mapSubject(x => convert(x).toDate(), x => LocalDate.from(nativeJs(x))), bind(xml.dateButton, buttonDate("date"), "input"));
        this.date.pipe(mapSubjectWithExisting(x => x.toLocalTime(), (a, b) => a.with(b))).pipe(mapSubject(x => convert(LocalDateTime.of(LocalDate.now(), x)).toDate(), x => LocalTime.from(nativeJs(x))), bind(xml.timeButton, buttonDate("time"), "input"));
        
        return view;
    }
}
