// File: /home/jivie/Projects/khrysalis-full-example/android/src/main/java/com/lightningkite/rxexample/vg/DateButtonDemoVG.kt
// Package: com.lightningkite.rxexample.vg
// Generated by Khrysalis - this file will be overwritten.
import { LocalDate, LocalDateTime, LocalTime, ZonedDateTime, convert, nativeJs } from '@js-joda/core'
import { BehaviorSubject } from 'rxjs'
import { ViewGenerator, buttonDate, mapSubject, mapSubjectWithExisting, subscribeAutoDispose } from 'rxjs-plus'
import { DateButtonDemoBinding } from '../resources/layouts/DateButtonDemoBinding'
import { FormatStyle, ofLocalizedDateTime } from 'khrysalis-runtime'
import { map } from 'rxjs/operators'

//! Declares com.lightningkite.rxexample.vg.DateButtonDemoVG
export class DateButtonDemoVG implements ViewGenerator {
    public static implementsViewGenerator = true;
    public constructor() {
        this.date = new BehaviorSubject(ZonedDateTime.now());
    }
    
    //! Declares com.lightningkite.rxexample.vg.DateButtonDemoVG.titleString
    public get titleString(): string { return "ZonedDateTime Button Demo"; }
    
    
    public readonly date: BehaviorSubject<ZonedDateTime>;
    
    public generate(dependency: Window): HTMLElement {
        const xml = DateButtonDemoBinding.inflate();
        const view = xml.root;
        
        this.date.pipe(map((it: ZonedDateTime): string => it.format(ofLocalizedDateTime(FormatStyle.MEDIUM, FormatStyle.MEDIUM)))).pipe(subscribeAutoDispose(xml.text, "textContent"));
        this.date.pipe(mapSubjectWithExisting(x => x.toLocalDate(), (a, b) => a.with(b))).pipe(mapSubject(x => convert(x).toDate(), x => LocalDate.from(nativeJs(x))), subscribeAutoDispose(xml.dateButton, buttonDate("date")));
        this.date.pipe(mapSubjectWithExisting(x => x.toLocalTime(), (a, b) => a.with(b))).pipe(mapSubject(x => convert(LocalDateTime.of(LocalDate.now(), x)).toDate(), x => LocalTime.from(nativeJs(x))), subscribeAutoDispose(xml.timeButton, buttonDate("time")));
        
        return view;
    }
}
