// Package: com.lightningkite.rxexample.vg
// Generated by Khrysalis - this file will be overwritten.
import { ExternalTestBinding } from '../resources/layouts/ExternalTestBinding'
import { ZonedDateTime, convert } from '@js-joda/core'
import { ViewGenerator, onThrottledEventDo, openEvent } from '@lightningkite/rxjs-plus'

//! Declares com.lightningkite.rxexample.vg.ExternalTestVG
export class ExternalTestVG implements ViewGenerator {
    public static implementsViewGenerator = true;
    public constructor() {
    }
    
    
    
    //! Declares com.lightningkite.rxexample.vg.ExternalTestVG.titleString
    public get titleString(): string { return "External Test"; }
    
    
    public generate(dependency: Window): HTMLElement {
        const xml = ExternalTestBinding.inflate();
        const view = xml.root;
        
        //--- Set Up xml.scrollView (overwritten on flow generation)
        
        //--- Set Up xml.openMap
        onThrottledEventDo(xml.openMap, 'click', (): void => {
            window.open(`https://www.google.com/maps/search/?api=1&query=${41.7269},${(-111.8432)}`, "_blank");
        });
        
        //--- Set Up xml.openWeb
        onThrottledEventDo(xml.openWeb, 'click', (): void => {
            window.open("https://lightningkite.com", "_blank");
        });
        
        //--- Set Up xml.openEvent
        onThrottledEventDo(xml.openEvent, 'click', (): void => {
            openEvent("A Virtual Lunch with LK", "Come eat virtual food with us!", "Lightning Kite in Logan Utah", convert(ZonedDateTime.now().plusDays(1).withHour(12).withMinute(0).withSecond(0)).toDate(), convert(ZonedDateTime.now().plusDays(1).withHour(13).withMinute(0).withSecond(0)).toDate());
        });
        
        //--- Generate End (overwritten on flow generation)
        
        return view;
    }
    
    //--- Init
    
    
    
    //--- Actions
    
    //--- Action openMapClick
    //--- Action openWebClick
    //--- Action openEventClick
    
    //--- Body End
}
