// Package: com.lightningkite.rxexample.vg
// Generated by Khrysalis - this file will be overwritten.

//! Declares com.lightningkite.rxexample.vg.HasTitle
export interface HasTitle {
    
    readonly title: string;
    
}
