// File: /home/jivie/Projects/khrysalis-full-example/android/src/main/java/com/lightningkite/rxexample/vg/LoadImageDemoVG.kt
// Package: com.lightningkite.rxexample.vg
// Generated by Khrysalis - this file will be overwritten.
import { HttpBody, Image, ViewGenerator, elementRemoved, imageElementSet, imageToBody, onThrottledEventDo, openFile, openFiles, subscribeAutoDispose } from 'rxjs-plus'
import { BehaviorSubject, map } from 'rxjs'
import { printStackTrace, runOrNull } from 'khrysalis-runtime'
import { LoadImageDemoBinding } from '../resources/layouts/LoadImageDemoBinding'

//! Declares com.lightningkite.rxexample.vg.LoadImageDemoVG
export class LoadImageDemoVG implements ViewGenerator {
    public static implementsViewGenerator = true;
    public constructor() {
        this.canUpload = new BehaviorSubject<(boolean | null)>(null);
        this.currentImage = new BehaviorSubject<(Image | null)>(null);
    }
    
    //! Declares com.lightningkite.rxexample.vg.LoadImageDemoVG.titleString
    public get titleString(): string { return "Load Image Demo"; }
    
    
    public readonly canUpload: BehaviorSubject<(boolean | null)>;
    public readonly currentImage: BehaviorSubject<(Image | null)>;
    
    public generate(dependency: Window): HTMLElement {
        const xml = LoadImageDemoBinding.inflate();
        const view = xml.root;
        
        elementRemoved(view).parts.push(this.currentImage.subscribe((it: (Image | null)): void => {
            this.canUpload.next(null);
        }, undefined, undefined));
        
        this.currentImage.pipe(subscribeAutoDispose(xml.image, (this_: HTMLImageElement, it: (Image | null)): void => {
            imageElementSet(xml.image, it);
        }));
        onThrottledEventDo(xml.camera, 'click', (): void => {
            openFile("image/*", undefined).subscribe((url: File): void => {
                this.currentImage.next({ uri: url });
            }, undefined);
        });
        onThrottledEventDo(xml.galleryMultiple, 'click', (): void => {
            openFiles("image/*").subscribe((urls: Array<File>): void => {
                const url_146 = (urls[0] ?? null);
                if (url_146 !== null) {
                    this.currentImage.next({ uri: url_146 });
                }
            }, undefined);
        });
        onThrottledEventDo(xml.gallery, 'click', (): void => {
            openFile("image/*").subscribe((url: File): void => {
                this.currentImage.next({ uri: url });
            }, undefined);
        });
        onThrottledEventDo(xml.loremPixel, 'click', (): void => {
            this.currentImage.next({ url: "https://picsum.photos/200" });
        });
        onThrottledEventDo(xml.checkCanUpload, 'click', (): void => {
            const i_165 = this.currentImage.value;
            if (i_165 !== null) {
                imageToBody(i_165, undefined, undefined).subscribe((it: HttpBody): void => {
                        this.canUpload.next(true);
                    }, (it: any): void => {
                        printStackTrace(it);
                        this.canUpload.next(false);
                });
            }
        });
        this.canUpload.pipe(map((it: (boolean | null)): string => it === null ? "Not checked" : it === true ? "Good to go!" : "FAILED!!!")).pipe(subscribeAutoDispose(xml.canUpload, "textContent"));
        return view;
    }
}
