// File: /home/jivie/Projects/khrysalis-full-example/android/src/main/java/com/lightningkite/rxexample/vg/LocationDemoVG.kt
// Package: com.lightningkite.rxexample.vg
// Generated by Khrysalis - this file will be overwritten.
import { BehaviorSubject, map } from 'rxjs'
import { ViewGenerator, onThrottledEventDo, requestLocation, subscribeAutoDispose } from '@lightningkite/rxjs-plus'
import { LocationDemoBinding } from '../resources/layouts/LocationDemoBinding'

//! Declares com.lightningkite.rxexample.vg.LocationDemoVG
export class LocationDemoVG implements ViewGenerator {
    public static implementsViewGenerator = true;
    public constructor() {
        this.locationInfo = new BehaviorSubject<(GeolocationCoordinates | null)>(null);
    }
    
    //! Declares com.lightningkite.rxexample.vg.LocationDemoVG.titleString
    public get titleString(): string { return "Location Demo"; }
    
    
    public readonly locationInfo: BehaviorSubject<(GeolocationCoordinates | null)>;
    
    public generate(dependency: Window): HTMLElement {
        const xml = LocationDemoBinding.inflate();
        const view = xml.root;
        onThrottledEventDo(xml.getLocation, 'click', (): void => {
            requestLocation(100.0).subscribe((location: GeolocationCoordinates): void => {
                this.locationInfo.next(location);
            }, undefined);
        });
        this.locationInfo.pipe(map((it: (GeolocationCoordinates | null)): string => {
            if (it !== null) {
                return `${it}`;
            } else {
                return "Nothing yet";
            }
        })).pipe(subscribeAutoDispose(xml.locationDisplay, "textContent"));
        return view;
    }
}
