// File: /home/jivie/Projects/khrysalis-full-example/android/src/main/java/com/lightningkite/rxexample/vg/SelectDemoVG.kt
// Package: com.lightningkite.rxexample.vg
// Generated by Khrysalis - this file will be overwritten.
import { LoadImageDemoVG } from './LoadImageDemoVG'
import { StackSubject, ViewGenerator, showIn, subscribeAutoDispose, xStackPush } from '@lightningkite/rxjs-plus'
import { ExampleContentVG } from './ExampleContentVG'
import { Observable, ObservableInput, fromEvent, of } from 'rxjs'
import { VideoDemoVG } from './VideoDemoVG'
import { SliderDemoVG } from './SliderDemoVG'
import { mergeMap, take } from 'rxjs/operators'
import { ExternalTestVG } from './ExternalTestVG'
import { BasicExampleVG } from './BasicExampleVG'
import { ComponentTestBinding } from '../resources/layouts/ComponentTestBinding'
import { LocationDemoVG } from './LocationDemoVG'
import { DateButtonDemoVG } from './DateButtonDemoVG'
import { LoginDemoVG } from './LoginDemoVG'
import { PreviewVG } from './PreviewVG'
import { first } from 'iter-tools-es'
import { ControlsDemoVG } from './ControlsDemoVG'
import { SelectDemoBinding } from '../resources/layouts/SelectDemoBinding'
import { WebsocketDemoVG } from './WebsocketDemoVG'
import { HttpDemoVG } from './HttpDemoVG'
import { ViewPagerDemoVG } from './ViewPagerDemoVG'

//! Declares com.lightningkite.rxexample.vg.SelectDemoVG
export class SelectDemoVG implements ViewGenerator {
    public static implementsViewGenerator = true;
    public readonly stack: StackSubject<ViewGenerator>;
    public constructor(stack: StackSubject<ViewGenerator>) {
        this.stack = stack;
        this.options = [new BasicExampleVG(), new VideoDemoVG(), new WebsocketDemoVG(), new HttpDemoVG(), new ExternalTestVG(), new DateButtonDemoVG(), new LocationDemoVG(), new LoginDemoVG(this.stack), new LoadImageDemoVG(), new ControlsDemoVG(), new ExampleContentVG(), new ViewPagerDemoVG(this.stack), new SliderDemoVG(), new PreviewVG()];
    }
    
    //! Declares com.lightningkite.rxexample.vg.SelectDemoVG.titleString
    public get titleString(): string { return "Select Demo"; }
    
    
    public readonly options: Array<ViewGenerator>;
    
    public selectVG(viewGenerator: ViewGenerator): void {
        xStackPush(this.stack, viewGenerator);
    }
    
    public generate(dependency: Window): HTMLElement {
        const xml = SelectDemoBinding.inflate();
        const view = xml.root;
        
        first(this.options)!;
        of(this.options).pipe(showIn(xml.list, (obs: Observable<ViewGenerator>): HTMLElement => {
            const xml = ComponentTestBinding.inflate();
            const view = xml.root;
            obs.pipe(subscribeAutoDispose(xml.label, (this_: HTMLElement, it: ViewGenerator): void => {
                this_.textContent = it.titleString;
            }));
            fromEvent(xml.button, "click", ev => ev.preventDefault()).pipe(mergeMap((it: void): ObservableInput<ViewGenerator> => obs.pipe(take(1)))).pipe(subscribeAutoDispose(view, (this_: HTMLDivElement, it: ViewGenerator): void => {
                this.selectVG(it);
            }));
            return view;
        }));
        
        return view;
    }
}
