// File: /home/jivie/Projects/khrysalis-full-example/android/src/main/java/com/lightningkite/rxexample/api/API.kt
// Package: com.lightningkite.rxexample.api
// Generated by Khrysalis - this file will be overwritten.
import KhrysalisRuntime
import Foundation

public var API: APIInterface = APIOnline()

