// Package: com.lightningkite.rxexample.api
// Generated by Khrysalis - this file will be overwritten.
import KhrysalisRuntime
import RxSwift
import Foundation

public protocol APIInterface: AnyObject {
    
    func getExamplePosts() -> Single<Array<Post>>
}


