// File: /home/jivie/Projects/khrysalis-full-example/android/src/main/java/com/lightningkite/rxexample/vg/ControlsDemoVG.kt
// Package: com.lightningkite.rxexample.vg
// Generated by Khrysalis - this file will be overwritten.
import KhrysalisRuntime
import RxSwift
import UIKit
import RxSwiftPlus
import Foundation

public class ControlsDemoVG : ViewGenerator {
    public init() {
        self.text = ValueSubject("")
        self.options = ValueSubject(["Apple", "Banana", "Chili Pepper", "Dragon Fruit"])
        self.number = ValueSubject(32)
        //Necessary properties should be initialized now
    }
    
    public var titleString: String {
        get { return "Controls Demo" }
    }
    
    public let text: ValueSubject<String>
    public let options: ValueSubject<Array<String>>
    public let number: ValueSubject<Int>
    
    public func generate(dependency: ViewControllerAccess) -> UIView {
        let xml = ControlsDemoBinding()
        let view = xml.root
        
        self.number.toSubjectString().bind(xml.numberText)
        self.text
            .bind(xml.editableText)
            .bind(xml.editableAutoText)
            .bind(xml.editableTextBig)
            .subscribeAutoDispose(xml.editableTextCopy, \.text)
        self.options
            .showIn(xml.editableAutoText, onItemSelected: self.text)
            .showIn(xml.spinner, selected: self.text)
        
        return view
    }
}

