// Package: com.lightningkite.rxexample.vg
// Generated by Khrysalis - this file will be overwritten.
import KhrysalisRuntime
import RxSwift
import UIKit
import RxSwiftPlus
import Foundation

public final class DateButtonDemoVG : ViewGenerator, HasTitle {
    public init() {
        self.date = ValueSubject(ZonedDateTime())
        //Necessary properties should be initialized now
    }
    
    public var title: String {
        get { return "ZonedDateTime Button Demo" }
    }
    
    public let date: ValueSubject<ZonedDateTime>
    
    public func generate(dependency: ViewControllerAccess) -> UIView {
        let xml = DateButtonDemoBinding()
        let view = xml.root
        
        self.date.map { (it) -> String in it.format(DateFormatter(dateStyle: DateFormatter.Style.medium, timeStyle: DateFormatter.Style.medium)) }
            .subscribeAutoDispose(xml.text, \UILabel.text)
        self.date.toSubjectLocalDate().bind(xml.dateButton)
        self.date.toSubjectLocalTime().bind(xml.timeButton)
        
        return view
    }
}

