// File: /home/jivie/Projects/khrysalis-full-example/android/src/main/java/com/lightningkite/rxexample/vg/ExampleContentVG.kt
// Package: com.lightningkite.rxexample.vg
// Generated by Khrysalis - this file will be overwritten.
import KhrysalisRuntime
import RxSwift
import UIKit
import RxSwiftPlus
import Foundation

public class ExampleContentVG : ViewGenerator {
    public init() {
        self.number = ValueSubject(0)
        self.chained = ValueSubject(ValueSubject(0))
        //Necessary properties should be initialized now
    }
    
    public var titleString: String {
        get { return "Example Content" }
    }
    
    public let number: ValueSubject<Int>
    public let chained: ValueSubject<ValueSubject<Int>>
    
    public func increment() -> Void {
        let temp26 = self.number
        temp26.value = self.number.value + 1
    }
    
    public func generate(dependency: ViewControllerAccess) -> UIView {
        let xml = ExampleContentBinding()
        let view = xml.root
        xml.exampleContentIncrement.onClick { () -> Void in self.increment() }
        self.number.map { (it) -> String in String(kotlin: it) }
            .subscribeAutoDispose(xml.exampleContentNumber, \UILabel.text)
        xml.chainedIncrement.onClick { () -> Void in self.chained.value.value = self.chained.value.value + 1 }
        self.chained.flatMap { (it) -> Observable<Int> in it }.map { (it) -> String in String(kotlin: it) }
            .subscribeAutoDispose(xml.chainedNumber, \UILabel.text)
        xml.scrollToTop.onClick { () -> Void in xml.scrollView.setContentOffset(CGPoint(x: CGFloat(0), y: CGFloat(0)), animated: true) }
        return view
    }
}

