// File: /home/jivie/Projects/khrysalis-full-example/android/src/main/java/com/lightningkite/rxexample/vg/ExternalTestVG.kt
// Package: com.lightningkite.rxexample.vg
// Generated by Khrysalis - this file will be overwritten.
import KhrysalisRuntime
import CoreLocation
import UIKit
import RxSwiftPlus
import Foundation

public class ExternalTestVG : ViewGenerator {
    public init() {
        //Necessary properties should be initialized now
    }
    
    
    
    public var titleString: String {
        get { return "External Test" }
    }
    
    public func generate(dependency: ViewControllerAccess) -> UIView {
        let xml = ExternalTestBinding()
        let view = xml.root
        
        //--- Set Up xml.scrollView (overwritten on flow generation)
        
        //--- Set Up xml.openMap
        xml.openMap.onClick { () -> Void in dependency.openMap(coordinate: CLLocationCoordinate2D(latitude: 41.7269, longitude: (-111.8432)), label: "Lightning Kite", zoom: 14) }
        
        //--- Set Up xml.openWeb
        xml.openWeb.onClick { () -> Void in dependency.openUrl(url: "https://lightningkite.com") }
        
        //--- Set Up xml.openEvent
        xml.openEvent.onClick { () -> Void in dependency.openEvent(title: "A Virtual Lunch with LK", description: "Come eat virtual food with us!", location: "Lightning Kite in Logan Utah", start: (ZonedDateTime().plus(day: 1).with(hour: 12).with(minute: 0).with(second: 0)).toDate(), end: (ZonedDateTime().plus(day: 1).with(hour: 13).with(minute: 0).with(second: 0)).toDate()) }
        
        //--- Generate End (overwritten on flow generation)
        
        return view
    }
    
    //--- Init
    
    
    
    //--- Actions
    
    //--- Action openMapClick
    //--- Action openWebClick
    //--- Action openEventClick
    
    //--- Body End
}

