// Package: com.lightningkite.rxexample.vg
// Generated by Khrysalis - this file will be overwritten.
import KhrysalisRuntime
import RxSwift
import CoreLocation
import UIKit
import RxSwiftPlus
import Foundation

public final class LocationDemoVG : ViewGenerator, HasTitle {
    public init() {
        self.locationInfo = (ValueSubject(nil as CLLocation?) as ValueSubject<CLLocation?>)
        //Necessary properties should be initialized now
    }
    
    public var title: String {
        get { return "Location Demo" }
    }
    
    public let locationInfo: ValueSubject<CLLocation?>
    
    public func generate(dependency: ViewControllerAccess) -> UIView {
        let xml = LocationDemoBinding()
        let view = xml.root
        xml.getLocation.onClick { () -> Void in dependency.requestLocation(accuracyBetterThanMeters: 100.0).subscribe(onSuccess: { (location) -> Void in self.locationInfo.value = location }) }
        self.locationInfo.map({ (it) -> String in if let it = it {
                return "\(it)"
            } else {
                return "Nothing yet"
        } }).subscribeAutoDispose(xml.locationDisplay, \UILabel.text)
        return view
    }
}

