// File: /home/jivie/Projects/khrysalis-full-example/android/src/main/java/com/lightningkite/rxexample/vg/SegmentedControlDemoVG.kt
// Package: com.lightningkite.rxexample.vg
// Generated by Khrysalis - this file will be overwritten.
import KhrysalisRuntime
import UIKit
import RxSwiftPlus
import Foundation

public class SegmentedControlDemoVG : ViewGenerator {
    public init() {
        //Necessary properties should be initialized now
    }
    
    public var titleString: String {
        get { return "Segmented Control Demo" }
    }
    
    public func generate(dependency: ViewControllerAccess) -> UIView {
        let xml = SegmentedControlDemoBinding()
        let view = xml.root
        
        xml.tabs.bind(tabs: ["A", "B", "C"], selected: ValueSubject("B"))
        xml.tabs2.bind(tabs: ["A", "B", "C", "D", "E", "F", "G"], selected: ValueSubject("B"))
        
        return view
    }
}

