// Package: com.lightningkite.rxexample.vg
// Generated by Khrysalis - this file will be overwritten.
import KhrysalisRuntime
import RxSwift
import UIKit
import RxSwiftPlus
import Foundation

public final class VideoDemoVG : ViewGenerator, HasTitle {
    public init() {
        self.currentVideo = (ValueSubject(VideoRemoteUrl(URL(string: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4")!) as Video) as ValueSubject<Video>)
        //Necessary properties should be initialized now
    }
    
    
    
    public var title: String {
        get { return "Video Demo" }
    }
    
    public let currentVideo: ValueSubject<Video>
    
    public func generate(dependency: ViewControllerAccess) -> UIView {
        let xml = VideoDemoBinding()
        let view = xml.root
        
        //--- Set Up xml.video
        self.currentVideo
            .subscribeAutoDispose(xml.video, { (this, it) -> Void in xml.video.setVideo(it, playWhenReady: false) })
        
        //--- Set Up xml.gallery
        xml.gallery.onClick { () -> Void in dependency
                .requestVideoGallery()
            .subscribe(onSuccess: { (it) -> Void in self.currentVideo.value = VideoLocalUrl(it) }) }
        
        //--- Set Up xml.camera
        xml.camera.onClick { () -> Void in dependency
                .requestVideoCamera()
            .subscribe(onSuccess: { (it) -> Void in self.currentVideo.value = VideoLocalUrl(it) }) }
        
        //--- Set Up xml.galleryMulti
        xml.galleryMulti.onClick { () -> Void in dependency
                .requestVideosGallery()
                .subscribe(onSuccess: { (it) -> Void in if let it = (it.firstOrNull()) {
                self.currentVideo.value = VideoLocalUrl(it)
        } }) }
        
        //--- Generate End (overwritten on flow generation)
        
        return view
    }
    
    //--- Init
    
    
    
    //--- Actions
    
    
    //--- Action galleryClick
    
    //--- Action cameraClick
    
    //--- Action galleryMultiClick
    
    //--- Body End
}

