// File: /home/jivie/Projects/khrysalis-full-example/android/src/main/java/com/lightningkite/rxexample/vg/ViewPagerDemoVG.kt
// Package: com.lightningkite.rxexample.vg
// Generated by Khrysalis - this file will be overwritten.
import KhrysalisRuntime
import UIKit
import RxSwiftPlus
import Foundation

public class ViewPagerDemoVG : ViewGenerator {
    public var stack: ValueSubject<Array<ViewGenerator>>
    public init(stack: ValueSubject<Array<ViewGenerator>>) {
        self.stack = stack
        self.items = ["First", "Second", "Third"]
        self.selectedIndex = ValueSubject(0)
        //Necessary properties should be initialized now
    }
    
    public var titleString: String {
        get { return "View Pager Demo" }
    }
    
    public let items: Array<String>
    public let selectedIndex: ValueSubject<Int>
    
    public func generate(dependency: ViewControllerAccess) -> UIView {
        let xml = ViewPagerDemoBinding()
        let view = xml.root
        
        self.items.showIn(xml.viewPager, showIndex: self.selectedIndex) { (it) -> UIView in
            let xml = ComponentTestBinding()
            let view = xml.root
            xml.label.text = it
            return view
        }
        
        return view
    }
}

