// Package: com.lightningkite.rxexample.vg
// Generated by Khrysalis - this file will be overwritten.
import KhrysalisRuntime
import RxSwift
import UIKit
import RxSwiftPlus
import Foundation

public final class ViewPagerDemoVG : ViewGenerator, HasTitle {
    public var stack: ValueSubject<Array<ViewGenerator>>
    public init(stack: ValueSubject<Array<ViewGenerator>>) {
        self.stack = stack
        self.selectedIndex = ValueSubject(0)
        //Necessary properties should be initialized now
    }
    
    public var title: String {
        get { return "View Pager Demo" }
    }
    
    public let selectedIndex: ValueSubject<Int>
    
    public func generate(dependency: ViewControllerAccess) -> UIView {
        let xml = ViewPagerDemoBinding()
        let view = xml.root
        
        Observable.just(["First", "Second", "Third"]).showIn(xml.viewPager, showIndex: self.selectedIndex) { (it) -> UIView in
            let xml = ComponentTestBinding()
            let view = xml.root
            it.subscribeAutoDispose(xml.label, \UILabel.text)
            return view
        }
        
        return view
    }
}

