use_frameworks!

platform :ios, '11.0'

target 'KhrysalisFullExample' do

  #target 'KhrysalisFullExample_Tests' do
  #  inherit! :search_paths
  #  
  #end
    pod 'RxSwift', :git => 'https://github.com/lightningkite/RxSwift.git', :branch => 'main'
    pod 'RxSwiftPlus', :git => 'https://github.com/lightningkite/RxSwiftPlus.git', :branch => 'master'
    pod 'XmlToXibRuntime', :git => 'https://github.com/lightningkite/android-xml-to-ios-xib.git', :branch => 'master'
    pod 'KhrysalisRuntime', :git => 'https://github.com/lightningkite/khrysalis.git', :branch => 'master'
    pod "RxCoreLocation", :git => 'https://github.com/RxSwiftCommunity/RxCoreLocation.git', :branch => 'master'
    pod "Cosmos", :git => 'https://github.com/lightningkite/Cosmos.git', :branch => 'master'
end
