use_frameworks!

platform :ios, '11.0'

target 'KhrysalisFullExample' do

  #target 'KhrysalisFullExample_Tests' do
  #  inherit! :search_paths
  #  
  #end
    pod 'RxSwift', :git => 'https://github.com/lightningkite/RxSwift.git', :branch => 'main'
    pod 'RxSwiftPlus', :git => 'https://github.com/lightningkite/RxSwiftPlus.git', :branch => 'master'
    pod 'XmlToXibRuntime', :git => 'https://github.com/lightningkite/android-layout-translator.git', :branch => 'master'
    pod 'KhrysalisRuntime', :git => 'https://github.com/lightningkite/khrysalis.git', :branch => 'master'
#   pod 'RxSwift', :path => '../../RxSwift/RxSwift.podspec'
#   pod 'RxSwiftPlus', :path => '../../RxSwiftPlus/RxSwiftPlus.podspec'
#   pod 'XmlToXibRuntime', :path => '../../android-layout-translator/XmlToXibRuntime/XmlToXibRuntime.podspec'
#   pod 'KhrysalisRuntime', :path => '../../khrysalis/ios-runtime/KhrysalisRuntime/KhrysalisRuntime.podspec'
    pod "RxCoreLocation", :git => 'https://github.com/RxSwiftCommunity/RxCoreLocation.git', :branch => 'master'
    pod "Cosmos", :git => 'https://github.com/lightningkite/Cosmos.git', :branch => 'master'
end
